import { prisma } from '../lib/prisma.js';

export async function seedBots() {
  try {
    const bots = [
      {
        supabaseId: 'bot_001_amina',
        email: 'amina@bot.velora.com',
        fullName: 'Amina Aden',
        gender: 'FEMALE',
        dateOfBirth: new Date('2001-05-12'),
        city: 'London',
        country: 'United Kingdom',
        religion: 'ISLAM',
        maritalStatus: 'NEVER_MARRIED',
        educationLevel: 'BACHELORS',
        career: 'Digital Designer',
        height: 168,
        relationshipGoal: 'MARRIAGE',
        bio: 'Somali designer in London ✨. Love photography, matching color palettes, and exploring quiet bookshops. Let\'s chat and see where it goes!',
        interests: ['Art', 'Design', 'Reading', 'Photography', 'Travel'],
        languages: ['Somali', 'English'],
        personalityTraits: ['Creative', 'Empathetic', 'Optimistic'],
        lifestylePrefs: ['Career-driven', 'Active', 'Social'],
        profilePhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
        photos: [
          'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800',
          'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=800'
        ],
        isVerified: true,
        verificationStatus: 'VERIFIED',
        isProfileComplete: true,
        profileCompletion: 100,
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        supabaseId: 'bot_002_leyla',
        email: 'leyla@bot.velora.com',
        fullName: 'Leyla Farah',
        gender: 'FEMALE',
        dateOfBirth: new Date('1999-09-18'),
        city: 'Minneapolis',
        country: 'United States',
        religion: 'ISLAM',
        maritalStatus: 'NEVER_MARRIED',
        educationLevel: 'BACHELORS',
        career: 'Dental Hygienist',
        height: 163,
        relationshipGoal: 'LONG_TERM',
        bio: 'Hey! I\'m Leyla. Family-first Somali-American. Love cooking traditional food with a modern twist, fitness, and late-night drives. ☕',
        interests: ['Cooking', 'Fitness', 'Family', 'Music', 'Hiking'],
        languages: ['Somali', 'English'],
        personalityTraits: ['Warm', 'Family-oriented', 'Funny'],
        lifestylePrefs: ['Health-conscious', 'Community-focused', 'Homebody'],
        profilePhoto: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=400',
        photos: [
          'https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=800',
          'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800'
        ],
        isVerified: true,
        verificationStatus: 'VERIFIED',
        isProfileComplete: true,
        profileCompletion: 100,
        latitude: 44.9778,
        longitude: -93.2650,
      },
      {
        supabaseId: 'bot_003_muna',
        email: 'muna@bot.velora.com',
        fullName: 'Muna Yusuf',
        gender: 'FEMALE',
        dateOfBirth: new Date('2002-11-04'),
        city: 'Toronto',
        country: 'Canada',
        religion: 'ISLAM',
        maritalStatus: 'NEVER_MARRIED',
        educationLevel: 'BACHELORS',
        career: 'Psychology Student',
        height: 165,
        relationshipGoal: 'MARRIAGE',
        bio: 'Psychology student in Toronto. Fascinated by human behavior, love writing, poetry, and nature walks. Looking for someone mature and intellectual.',
        interests: ['Psychology', 'Writing', 'Nature', 'Poetry', 'Travel'],
        languages: ['Somali', 'English', 'Arabic'],
        personalityTraits: ['Thoughtful', 'Quiet', 'Analytical'],
        lifestylePrefs: ['Career-driven', 'Active', 'Homebody'],
        profilePhoto: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?w=400',
        photos: [
          'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?w=800',
          'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800'
        ],
        isVerified: true,
        verificationStatus: 'VERIFIED',
        isProfileComplete: true,
        profileCompletion: 100,
        latitude: 43.6532,
        longitude: -79.3832,
      },
      {
        supabaseId: 'bot_004_hassan',
        email: 'hassan@bot.velora.com',
        fullName: 'Hassan Bile',
        gender: 'MALE',
        dateOfBirth: new Date('1997-03-22'),
        city: 'Stockholm',
        country: 'Sweden',
        religion: 'ISLAM',
        maritalStatus: 'NEVER_MARRIED',
        educationLevel: 'MASTERS',
        career: 'Software Engineer',
        height: 184,
        relationshipGoal: 'MARRIAGE',
        bio: 'Software engineer living in Stockholm. Passionate about technology, football, and fitness. Looking for a smart, kind partner to build a future together.',
        interests: ['Football', 'Technology', 'Fitness', 'Cooking', 'Hiking'],
        languages: ['Somali', 'English', 'Swedish'],
        personalityTraits: ['Outgoing', 'Ambitious', 'Empathetic'],
        lifestylePrefs: ['Career-driven', 'Active', 'Tech-savvy'],
        profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        photos: [
          'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800',
          'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800'
        ],
        isVerified: true,
        verificationStatus: 'VERIFIED',
        isProfileComplete: true,
        profileCompletion: 100,
        latitude: 59.3293,
        longitude: 18.0686,
      },
      {
        supabaseId: 'bot_005_abdirahman',
        email: 'abdirahman@bot.velora.com',
        fullName: 'Abdirahman Warsame',
        gender: 'MALE',
        dateOfBirth: new Date('1995-08-14'),
        city: 'Columbus',
        country: 'United States',
        religion: 'ISLAM',
        maritalStatus: 'NEVER_MARRIED',
        educationLevel: 'BACHELORS',
        career: 'Real Estate Developer',
        height: 180,
        relationshipGoal: 'MARRIAGE',
        bio: 'Real estate developer based in Columbus. Focused on building my career and community. Looking for an ambitious Somali woman who values family and support.',
        interests: ['Real Estate', 'Business', 'Travel', 'Reading', 'Community'],
        languages: ['Somali', 'English'],
        personalityTraits: ['Confident', 'Ambitious', 'Family-oriented'],
        lifestylePrefs: ['Career-driven', 'Active', 'Community-focused'],
        profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        photos: [
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
          'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800'
        ],
        isVerified: true,
        verificationStatus: 'VERIFIED',
        isProfileComplete: true,
        profileCompletion: 100,
        latitude: 39.9612,
        longitude: -82.9988,
      },
    ];

    for (const bot of bots) {
      await prisma.user.upsert({
        where: { supabaseId: bot.supabaseId },
        create: bot as any,
        update: bot as any,
      });
    }
    console.log('🤖 Auto-seeded 5 beautiful sample bots successfully!');
  } catch (error) {
    console.error('❌ Failed to seed bots:', error);
  }
}
